In [1]:
import numpy as np
import pandas as pd

### Numpy

In [2]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
arr2 = np.arange(9).reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [4]:
np.concatenate((arr1,arr2))            # 垂直拼接

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate((arr1,arr2),axis = 1)    # 水平拼接

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

### Series

In [6]:
s1 = pd.Series([1,2,3],index=['A','B',"C"])
s2 = pd.Series([4,5], index = ['X','Y'])

In [7]:
s1

A    1
B    2
C    3
dtype: int64

In [8]:
s2

X    4
Y    5
dtype: int64

In [9]:
pd.concat((s1,s2))          # 垂直拼接

A    1
B    2
C    3
X    4
Y    5
dtype: int64

In [12]:
pd.concat((s1,s2),axis=1)     # 返回一个dataframe

0    1
A  1.0  NaN
B  2.0  NaN
C  3.0  NaN
X  NaN  4.0
Y  NaN  5.0

### DataFrame

In [14]:
df1 = pd.DataFrame(data = np.random.randint(10,size=(4,3)), columns=['X','Y','Z'])
df1

X  Y  Z
0  8  3  2
1  5  9  6
2  4  0  0
3  5  4  7

In [16]:
df2 = pd.DataFrame(data = np.random.randint(10,size=(3,3)), columns=['X','Y','A'])
df2

X  Y  A
0  1  0  7
1  7  3  5
2  7  0  7

In [19]:
pd.concat((df1,df2))

A  X  Y    Z
0  NaN  8  3  2.0
1  NaN  5  9  6.0
2  NaN  4  0  0.0
3  NaN  5  4  7.0
0  7.0  1  0  NaN
1  5.0  7  3  NaN
2  7.0  7  0  NaN

### combine   如果自己没有的，就用另一个来填充

In [22]:
s1 = pd.Series(data=[2,np.nan,4,np.nan], index=['A','B','C','D'])
s1

A    2.0
B    NaN
C    4.0
D    NaN
dtype: float64

In [23]:
s2 = pd.Series(data=[1,2,3,4], index=['A','B','C','D'])
s2

A    1
B    2
C    3
D    4
dtype: int64

In [24]:
s1.combine_first(s2)

A    2.0
B    2.0
C    4.0
D    4.0
dtype: float64

In [28]:
df1 = pd.DataFrame(data={
    'X':[1,2,3,np.nan],
    'Y':[1,2,np.nan,4]
})
df2 = pd.DataFrame(data={
    'X':[1,2,3,4],
    'Y':[1,2,3,4]
})
df1.combine_first(df2)

X    Y
0  1.0  1.0
1  2.0  2.0
2  3.0  3.0
3  4.0  4.0