In [2]:
import pickle
import numpy as np

### 传统python的序列化方式

In [15]:
x = np.random.randint(5,size=(3,3))
f = open('x.txt','wb')
pickle.dump(x,f)
f.close()

In [16]:
f = open('x.txt','rb')
print(pickle.load(f))
f.close()

[[2 3 4]
 [3 0 2]
 [2 0 1]]


### numpy的序列方式

In [22]:
arr = np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.save('arr.npy',arr)

In [24]:
np.load('arr.npy')

array([[0., 0., 0.],
       [0., 0., 0.]])

### 将多个数组序列化到一个文件内

In [25]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.savez('arrays',arr1 = x, arr2 = y)

In [29]:
xy = np.load('arrays.npz')
xy

In [30]:
xy['arr1']

array([1, 2, 3])

In [31]:
xy['arr2']

array([4, 5, 6])