In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(10,size=(2,3))
arr1

array([[2, 9, 2],
       [2, 4, 0]])

<hr>

In [4]:
np.unique(arr1)    # 显示数组中出现了哪些数

array([0, 2, 4, 9])

<hr>

In [5]:
sum(arr1)   # 求arr1每一列的和

array([ 4, 13,  2])

In [6]:
sum(arr1[0])  # arr1一行的和

13

In [7]:
sum(arr1)[0]   # arr1第一列的和

4

In [9]:
sum(arr1[:,0])  # arr1第一列的和

4

 <hr>

In [11]:
arr1.max()   # 找最大值

9

In [13]:
arr1[1].max()

4