In [4]:
import numpy as np

### 通过list创建数组

In [2]:
list_1 = [1,2,3,4]  
array_1 = np.array(list_1)
array_1

array([1, 2, 3, 4])

In [4]:
list_2 = [5,6,7,8]
array_2 = np.array([list_1, list_2])
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

### array里的属性

In [5]:
array_2.shape            # shape 显示数组是几行几列

(2, 4)

In [6]:
array_2.size            # size 显示数组中的元素数量

8

In [7]:
array_2.dtype         # dtype 显示元素的类型

dtype('int32')

In [9]:
array_3 = np.array([1,'miku'])  # 若类型不一致，则
array_3.dtype

dtype('<U11')

### 通过arange创建数组 （与python中的range用法相同）

In [10]:
array_4 = np.arange(0,10)
array_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_5 = np.arange(0,10,2)
array_5

array([0, 2, 4, 6, 8])

### 通过zeros创建全零数组,通过ones创建全1数组

In [13]:
array_6 = np.zeros(5)
array_6

array([0., 0., 0., 0., 0.])

In [15]:
array_7 = np.zeros([2,3])
array_7

array([[0., 0., 0.],
       [0., 0., 0.]])

In [3]:
array_8 = np.ones([3,3])
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 通过eye创建单位数组

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 访问数组

In [19]:
a = np.array([1,2,3,4])
a[1]

2

In [24]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
b[0][1]

2

In [26]:
b[0,1]

2

### 切片

In [27]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
c[0:2,1:2]

array([[2],
       [5]])

### 条件判断

In [5]:
arr = np.random.randint(5,size=(3,3))
arr

array([[3, 3, 1],
       [4, 2, 0],
       [1, 2, 1]])

In [6]:
arr > 3

array([[False, False, False],
       [ True, False, False],
       [False, False, False]])

In [7]:
arr != 1

array([[ True,  True, False],
       [ True,  True,  True],
       [False,  True, False]])

In [8]:
np.where(arr != 0 , 1 , 0)  # 三目运算，如果数值不等于0则变成1，否则变成0

array([[1, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])