In [5]:
import numpy as np

### 快速创建随机数组

In [3]:
np.random.randn(10)   # 符合正态分布

array([-2.11788181, -0.80767543,  0.77168867,  0.88768899, -1.31274441,
       -0.93637771, -0.20347031, -0.6088137 , -0.51034652,  1.25040735])

In [20]:
np.random.randint(10) # 返回一个10以内的随机数（不包括10）

0

In [21]:
np.random.randint(10, size = (2,3))  # 返回一个数组

array([[9, 3, 8],
       [9, 9, 4]])

In [23]:
np.random.randint(5, size = 10)   # 返回10个5以内的整数

array([0, 0, 3, 2, 0, 4, 1, 2, 3, 4])

### 重塑reshape

In [25]:
a = np.array([1,2,3,4,5,6])
b = a.reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

### 数组运算 加减乘除

In [28]:
arr1 = np.random.randint(10,size=(4,5))
arr2 = np.random.randint(10,size=(4,5))

In [29]:
arr1

array([[9, 1, 9, 9, 7],
       [3, 1, 1, 2, 3],
       [0, 3, 5, 1, 7],
       [9, 9, 1, 3, 4]])

In [30]:
arr2

array([[1, 0, 9, 3, 6],
       [3, 6, 8, 5, 7],
       [1, 6, 9, 7, 6],
       [5, 9, 6, 1, 6]])

In [31]:
arr1 + arr2

array([[10,  1, 18, 12, 13],
       [ 6,  7,  9,  7, 10],
       [ 1,  9, 14,  8, 13],
       [14, 18,  7,  4, 10]])

In [32]:
arr1 - arr2

array([[ 8,  1,  0,  6,  1],
       [ 0, -5, -7, -3, -4],
       [-1, -3, -4, -6,  1],
       [ 4,  0, -5,  2, -2]])

In [33]:
arr1 * arr2

array([[ 9,  0, 81, 27, 42],
       [ 9,  6,  8, 10, 21],
       [ 0, 18, 45,  7, 42],
       [45, 81,  6,  3, 24]])

In [8]:
a = np.random.rand(10)
a

array([0.00491334, 0.94476301, 0.55349763, 0.5798881 , 0.44734917,
       0.10938963, 0.39327239, 0.24946104, 0.80792159, 0.86201828])

In [9]:
a + 1

array([1.00491334, 1.94476301, 1.55349763, 1.5798881 , 1.44734917,
       1.10938963, 1.39327239, 1.24946104, 1.80792159, 1.86201828])

In [10]:
a * 10

array([0.04913344, 9.44763014, 5.53497632, 5.79888099, 4.47349175,
       1.09389635, 3.93272386, 2.49461038, 8.07921588, 8.62018278])

### 创建矩阵（matrix）   （与array基本一样）

In [35]:
mat1 = np.mat([1,2,3,4])
mat1

matrix([[1, 2, 3, 4]])

In [39]:
mat2 = np.mat([[1,2,3],[4,5,6]])
mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [36]:
mat1.size

4

In [37]:
mat1.shape

(1, 4)

In [38]:
mat1.dtype

dtype('int32')

### mat和array的相互转换

In [40]:
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [41]:
m1 = np.mat(a1)
m1

matrix([[1, 2, 3]])

In [42]:
m2  = np.mat([1,2])
m2

matrix([[1, 2]])

In [43]:
a2 = np.array(m2)
a2

array([[1, 2]])

### 矩阵运算

In [47]:
mat_1 = np.mat(arr1)
mat_2 = np.mat(arr2)

In [50]:
mat_1

matrix([[9, 1, 9, 9, 7],
        [3, 1, 1, 2, 3],
        [0, 3, 5, 1, 7],
        [9, 9, 1, 3, 4]])

In [51]:
mat_2

matrix([[1, 0, 9, 3, 6],
        [3, 6, 8, 5, 7],
        [1, 6, 9, 7, 6],
        [5, 9, 6, 1, 6]])

In [48]:
mat_1 + mat_2

matrix([[10,  1, 18, 12, 13],
        [ 6,  7,  9,  7, 10],
        [ 1,  9, 14,  8, 13],
        [14, 18,  7,  4, 10]])

In [52]:
mat_1 - mat_2

matrix([[ 8,  1,  0,  6,  1],
        [ 0, -5, -7, -3, -4],
        [-1, -3, -4, -6,  1],
        [ 4,  0, -5,  2, -2]])

In [55]:
mat_1.reshape(4,5) * mat_2.reshape(5,4)    # 矩阵相乘，前一个矩阵的列数等于后一个矩阵的行数

matrix([[204, 171, 157, 176],
        [ 59,  42,  49,  51],
        [115,  93,  36, 101],
        [131,  79, 158, 144]])

In [7]:
arr1 = np.array([[1,2],[2,3]])             # 矩阵相乘
arr2 = np.array([[3,4],[5,6]])
np.dot(arr1,arr2)

array([[13, 16],
       [21, 26]])

#### 矩阵拼接

In [14]:
a1 = np.array([[1,2,3,4],[5,6,7,8]])
a2 = np.array([[9,10,11,12],[13,14,15,16]])

In [15]:
np.vstack((a1,a2))    # 竖直拼接

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [16]:
np.hstack((a1,a2))  # 水平拼接

array([[ 1,  2,  3,  4,  9, 10, 11, 12],
       [ 5,  6,  7,  8, 13, 14, 15, 16]])