In [1]:
import numpy as np

In [2]:
arr = np.random.randint(10, size = (5,5))
arr

array([[6, 1, 1, 6, 1],
       [6, 8, 5, 7, 0],
       [0, 5, 9, 5, 1],
       [5, 5, 0, 4, 3],
       [6, 8, 6, 4, 9]])

In [6]:
np.amax(arr)     # 最大值

9

In [3]:
np.amax(arr, axis=0)   # 每一列的最大值

array([6, 8, 9, 7, 9])

In [4]:
np.amax(arr, axis=1) # 每一行的最大值

array([6, 8, 9, 5, 9])

In [5]:
np.mean(arr)    # 平均值

4.44

In [7]:
np.mean(arr, axis=0) # 每一列的平均值

array([4.6, 5.4, 4.2, 5.2, 2.8])

In [8]:
np.mean(arr, axis = 1) # 每一行的平均值

array([3. , 5.2, 4. , 3.4, 6.6])

In [9]:
np.amin(arr)  # 最小值

0

In [10]:
np.amin(arr, axis = 0) #每一列的最小值

array([0, 1, 0, 4, 0])

In [11]:
np.amin(arr, axis = 1) # 每一行的最小值

array([1, 0, 0, 0, 4])

In [12]:
np.std(arr)   # 求方差

2.8011426240018555

In [13]:
np.std(arr, axis = 0)  # 每一列的方差

array([2.33238076, 2.57681975, 3.31058907, 1.16619038, 3.24961536])

In [14]:
np.std(arr, axis = 1) # 每一行的方差

array([2.44948974, 2.78567766, 3.2249031 , 1.8547237 , 1.74355958])